config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'

  resources :users, only: [:show] do 
    member do 
      post :add_friend
      get :show_friend_requests, :share_locations, :friends_locations
      put :accept_friend
    end

    resources :shared_locations, only: [:create, :destroy]

    resources :locations
  end

  get '/search' => 'search#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :latitude, :longitude, :user
end

app/models/shared_location.rb
class SharedLocation < ActiveRecord::Base
  validates_presence_of :user, :location , :share_with_id

  belongs_to :user
  belongs_to :share_with, class_name: 'User'
  belongs_to :location
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :locations, dependent: :destroy

  has_many :user_friends, dependent: :destroy
  has_many :friends, through: :user_friends, source: :friend

  #user whoreceives frnd request
  has_many :friend_requests, -> {where(accepted_at: nil) }, class_name: 'UserFriend', foreign_key: :friend_id
  has_many :friend_requests_sender, through: :friend_requests, source: :user

  has_many :shared_locations, dependent: :destroy

  has_many :shared_locations_by, class_name: 'SharedLocation', foreign_key: :share_with_id
  has_many :locations_shared_with_me, through: :shared_locations_by, source: :location  

  def image_url
    "/assets/user.png"
  end

  def friend_requests_sent_to?(u)
    user_friends.not_accepted.where(friend_id: u.id).exists?
  end

  def friends_of?(u)
    user_friends.where(friend_id: u.id).accepted.exists?
  end

end

app/models/user_friend.rb
class UserFriend < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validates_presence_of :user, :friend

  scope :accepted, -> { where.not(accepted_at: nil) }
  scope :not_accepted, -> { where(accepted_at: nil) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = current_user.locations
  end

  def create
    location = current_user.locations.build(longitude: params[:longitude], latitude: params[:latitude])
    location.save
    render nothing: true
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    if params[:query].present?
      @current_user_friend_ids = current_user.friend_ids
      @users = User.where("name like '%#{params[:query]}%' OR email like '%#{params[:query]}%'").where.not(id: current_user.id).includes(:friends)
    else
      @users = []
    end
  end

end

app/controllers/shared_locations_controller.rb
class SharedLocationsController < ApplicationController
  def create
    @shared_location = current_user.shared_locations.build(share_with_id: params[:user_id], location_id: params[:location_id])
    @shared_location.save
    render layout: false
  end

    def destroy
      @shared_location = current_user.shared_locations.find(params[:id])
      @shared_location.destroy
      render layout: false
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @friends = current_user.friends.where.not(user_friends: {accepted_at: nil})
  end

  def add_friend
    @user = User.find(params[:id])
    current_user.friends << @user
    @current_user_friend_ids = current_user.friend_ids
  end

  def show_friend_requests
    @senders = current_user.friend_requests_sender
    render layout: false
  end

  def accept_friend
    user = current_user.friend_requests_sender.find(params[:id])
    user_friend = current_user.user_friends.build(friend_id: user.id, accepted_at: Time.now)

    user.user_friends.where(user_friends: { friend_id: current_user.id }).update_all(accepted_at: Time.now) if user_friend.save
    render layout: false
  end

  def share_locations
    @location = current_user.locations.find(params[:location_id])
    @share_locations = current_user.shared_locations.where(location_id: @location.id)
    @share_with_ids = @share_locations.pluck(:share_with_id)
    @friends = current_user.friends.where.not(user_friends: {accepted_at: nil})
    render layout: false
  end

  def friends_locations
    @locations = current_user.locations_shared_with_me.includes(:user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def unobtrusive_js(code)
    if request.xhr?
      javascript_tag(code)
    else
      @unobtrusive_js ||= []
      @unobtrusive_js << code
      nil
    end
  end

  def include_unobtrusive_js
    @unobtrusive_js ||= []
    javascript_tag(@unobtrusive_js.join(';\n'))
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to "Home", root_path %></li>

        <% if current_user %>
          <li><%= link_to "Friends", user_path(current_user) %></li>
          <li><%= link_to "My Locations", user_locations_path(current_user) %></li>
          <li><%= link_to "My Friends Locations", friends_locations_user_path(current_user) %></li>
        <% end %>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user && frnd_req_count = current_user.friend_requests_sender.count %>
          <% if frnd_req_count > 0 %> 
            <li class="friend-requests">
              <span class="fa fa-user-plus">
                <%= link_to frnd_req_count, 
                show_friend_requests_user_path(current_user), data: { remote_popup: true, title: "Friend Requests", modal_class: "fr-modal" }, class: "friend-requests__count", title: "Friend Requests" %>
              </span>
            </li>
          <% end %>
        <% end %>
        <% if current_user %>
          <li><%= form_tag(search_path, method: :get, class: "form-inline search-form") do %>
            <div class="search-input">
              <%= text_field_tag(:query, params[:query], placeholder: "Search users", class: "input-value") %>
            </div>
            <% end %>
          </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>

          <ul class="dropdown-menu">
            <% if current_user %>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Share your location</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'shared/flash' %>
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= include_unobtrusive_js%>
</body>
</html>

app/views/locations/index.html.erb
<h3>My Maps</h3>
<span class="text-muted">To check in to one place click the desired location on the map. Share location with friends by clicking particular location's checkin time.</span>

<div id="map" class="map" style="width=100%; height: 600px" tabindex="0" data-user="<%= current_user.id %>" data-locations="<%= @locations.to_json %>"></div>

<div style="display: none;">
  <% @locations.each_with_index do |location, index| %>
    <a id="loc-<%= index + 1 %>" data-location=<%= location.id %> href="#" class="location-text"><%= location.created_at.strftime("%d/%m/%Y %I:%M %p") %></a>
    <div id="marker-<%= index+1 %>" title="Marker" class="marker"></div>
  <% end %>
</div>
<%= unobtrusive_js("LS.Map.initMap();  LS.Map.addClickEvent();") %>

app/views/search/_user.html.erb
    <p class="searched-result__user__image"><%= image_tag user.image_url %></p>
    <p class="text-center"><%= user.name %></p>
    <p><% if current_user.friend_requests_sent_to?(user) %>
        <span class="label label-info">Request Sent</span>
      <% elsif current_user.friends_of?(user) %>
        <span class="label label-success">Friends</span>
      <% else %>
        <%= link_to "Add friend", add_friend_user_path(user), method: :post, remote: true, class: "btn btn-primary btn-xs" %>
      <% end %>
    </p>

app/views/search/index.html.erb
<h3>Search Results</h3>

<div class="search-result">
<div class="row">
  <% @users.in_groups_of(6, false) do |users| %>
    <% users.each do |user| %>
      <div class="col-sm-2 col-md-2">
        <div class="user-<%= user.id %> searched-result__user">
          <%= render 'user', user: user %>
        </div>
      </div>  
    <% end %>
  <% end %>
  </div>

app/views/shared/_flash.html.erb
<% if flash.present? %>
  <% flash.each do |key, value| %>
    <% if value.present? %>
      <div id="flash-messages" class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  <% end %>
<% end %>

app/views/shared_locations/create.js.erb
$(".user-share-<%= @shared_location.share_with_id %>").html('<%= link_to "Stop Sharing", user_shared_location_path(@shared_location.share_with_id, @shared_location.id), method: :delete, remote: true, class: "btn btn-xs btn-primary" %>');

app/views/shared_locations/destroy.js.erb
$(".user-share-<%= @shared_location.share_with_id %>").html('<%= link_to "Share", user_shared_locations_path(@shared_location.share_with_id, location_id: @shared_location.location_id), method: :post, remote: true, class: "btn btn-xs btn-primary" %>');

app/views/users/accept_friend.js.erb
$(".user-accept-<%= params[:id] %>").html("Accepted");

app/views/users/add_friend.js.erb
$(".user-<%= @user.id %>").html("<%= j(render 'search/user', user: @user) %>")

app/views/users/friends_locations.html.erb
<h3>My Friends Maps</h3>
<div id="map" class="map" style="width=100%; height: 600px" tabindex="0" data-user="<%= current_user.id %>" data-locations="<%= @locations.to_json %>"></div>

<div style="display: none;">
  <% @locations.each_with_index do |location, index| %>
    <a id="loc-<%= index + 1 %>" data-location=<%= location.id %> href="#" class="frnd-location-text"><%= location.user.name %>(<%= location.created_at.strftime("%d/%m/%Y %I:%M %p") %>)</a>
    <div id="marker-<%= index+1 %>" title="Marker" class="marker"></div>
  <% end %>
</div>
<%= unobtrusive_js("LS.Map.initMap();") %>

app/views/users/share_locations.html.erb
<div class="row">
  <% @friends.in_groups_of(3, false) do |users| %>
    <% users.each do |u| %>
      <div class="col-md-4 user-<%= u.id %>">
        <p class="text-center"><%= image_tag u.image_url %></p>
        <p class="text-center"><%= u.name %></p>
        <p class="text-center user-share-<%= u.id %>">
          <% if @share_with_ids.include?(u.id) %>
            <% s = @share_locations.detect {|s| s.share_with_id == u.id} %>
            <%= link_to "Stop Sharing", user_shared_location_path(s.share_with_id, s.id), method: :delete, remote: true, class: "btn btn-xs btn-danger" %>
          <% else %>
            <%= link_to "Share", user_shared_locations_path(u, location_id: @location.id), method: :post, remote: true, class: "btn btn-xs btn-primary" %>
          <% end %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <div class="user-details">
      <p class="text-center"><%= image_tag current_user.image_url %></p>
      <p class="text-center"><%= current_user.name %></p>
      <p class="text-center"><%= current_user.email %></p>
    </div>
  </div>

  <div class="col-sm-9">
    <div class="friend-list">
      <h3 class="friend-list__header">Friends (<%= @friends.count %>)</h3>
      <div class="row">
        <% @friends.in_groups_of(4, false) do |users| %>
        <% users.each do |user| %>
        <div class="col-sm-3">
          <div class="friend-list__profile">
            <p class="friend-list__profile__image"><%= image_tag user.image_url %></p>
            <p class="text-center"><%= user.name %></p>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show_friend_requests.html.erb
<div class="row">
  <% @senders.in_groups_of(2, false) do |users| %>
    <% users.each do |u| %>
      <div class="col-md-6 user-<%= u.id %>">
        <p class="text-center"><%= image_tag u.image_url %></p>
        <p class="text-center"><%= u.name %></p>
        <p class="text-center user-accept-<%= u.id %>"><%= link_to "Accept", accept_friend_user_path(u), method: :put, remote: true, class: "btn btn-sm btn-primary" %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="center">
    <div class="col-sm-12 col-md-12 colmd-offset-1">
      <h3 class="text-center">Welcome To Location Sharing App</h3>
      <p class="text-center text-muted">Share your locations with friends.</p>
    </div>
  </div>
</div>